import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

export async function POST(request: NextRequest) {
	try {
		if (!process.env.GEMINI_API_KEY) {
			throw new Error("GEMINI_API_KEY is not set");
		}

		const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

		const formData = await request.formData();
		const personImage = formData.get("personImage") as File;
		const productImage = formData.get("productImage") as File;

		// Validate that both images were provided
		if (!personImage || !productImage) {
			return NextResponse.json(
				{ error: "Both person image and product image are required" },
				{ status: 400 }
			);
		}

		// Validate file types
		const validTypes = ["image/jpeg", "image/jpg", "image/png", "image/webp"];
		if (!validTypes.includes(personImage.type) || !validTypes.includes(productImage.type)) {
			return NextResponse.json(
				{ error: "Invalid file type. Please upload JPEG, PNG, or WebP images" },
				{ status: 400 }
			);
		}

		// Convert images to base64 for processing
		const personBuffer = await personImage.arrayBuffer();
		const productBuffer = await productImage.arrayBuffer();

		const personBase64 = Buffer.from(personBuffer).toString("base64");
		const productBase64 = Buffer.from(productBuffer).toString("base64");

		const prompt = [
			{
				text: "The first image is of a person, and the second image is of a product. Combine these two images into a single image that showcases the person interacting with or using the product in a natural and appealing way. Ensure the lighting, perspective, and style are consistent across both images to create a seamless integration."
			},
			{
				inlineData: {
					mimeType: personImage.type,
					data: personBase64
				}
			},
			{
				inlineData: {
					mimeType: productImage.type,
					data: productBase64
				}
			}
		];

		const response = await ai.models.generateContent({
			model: "gemini-2.5-flash-image",
			contents: prompt,
		});

		// Check if response is valid
		if (!response?.candidates?.[0]?.content?.parts) {
			throw new Error("Invalid response from AI model");
		}

		// Extract the generated image
		let resultImageBase64 = "";
		let resultImageMimeType = "image/png";

		for (const part of response.candidates[0].content.parts) {
			if (part.text) {
				console.log("AI Response:", part.text);
			} else if (part.inlineData?.data) {
				resultImageBase64 = part.inlineData.data;
				resultImageMimeType = part.inlineData.mimeType || "image/png";
			}
		}

		// Return the generated image
		if (!resultImageBase64) {
			throw new Error("No image generated by AI model");
		}

		return NextResponse.json({
			success: true,
			message: "Images combined successfully",
			resultImage: `data:${resultImageMimeType};base64,${resultImageBase64}`,
		}, { status: 200 });
	} catch (error) {
		console.error("Error processing images:", error);
		return NextResponse.json(
			{ error: "Failed to process images" },
			{ status: 500 }
		);
	}
}
